version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package

  build:
    commands:
      - echo "Copying source files..."
      - cp lambda_function.py knowledge.txt requirements.txt package/
      - cd package
      - echo "Zipping files for Lambda deployment (excluding venv)..."
      - zip -r ../lambda-deployment.zip . -x ".venv/*" "venv/*"
      - cd ..

  post_build:
    commands:
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name TicTacToeLambda --zip-file fileb://lambda-deployment.zip

artifacts:
  files:
    - lambda-deployment.zip
