version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo "Copying source files..."
      - cp lambda_function.py knowledge.txt package/
      - cd package
      - echo "Zipping files..."
      - zip -r ../lambda-deployment.zip .
artifacts:
  files:
    - lambda-deployment.zip
